version: '3.1'

services:
  php-fpm:
    image: 'php-fpm'
    build: ./docker/php-fpm
    environment:
      PHP_SESSION_SAVE_PATH: 'tcp://redis:6379?auth=umasenhamuitocomplexa'
      XDEBUG_SESSION: 1
    volumes:
      - './docker/php-fpm/html:/var/www/html'
    ports:
      - 80:80
      - 443:443
    links:
      - 'redis'
  redis:
    build: ./docker/redis
